global:
  scrape_interval: 5s

scrape_configs:
  - job_name: shopping-admin-job
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:9092' ]
  - job_name: shopping-user-job
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:9093' ]